# Generated by Django 4.1.2 on 2022-11-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
