# Generated by Django 4.1.2 on 2022-12-01 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_validity_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validity_expiry_date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
