# Generated by Django 4.1.2 on 2022-12-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PMST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_stamp', models.DateTimeField()),
                ('pmst_1_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_1_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_1_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_1_temp', models.FloatField(blank=True, null=True)),
                ('pmst_2_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_2_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_2_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_2_temp', models.FloatField(blank=True, null=True)),
                ('pmst_3_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_3_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_3_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_3_temp', models.FloatField(blank=True, null=True)),
                ('pmst_4_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_4_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_4_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_4_temp', models.FloatField(blank=True, null=True)),
                ('pmst_5_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_5_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_5_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_5_temp', models.FloatField(blank=True, null=True)),
                ('pmst_6_status_int', models.IntegerField(blank=True, null=True)),
                ('pmst_6_status', models.CharField(blank=True, max_length=50, null=True)),
                ('pmst_6_quantity', models.FloatField(blank=True, null=True)),
                ('pmst_6_temp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
